# AI Jubilee Debate Configuration - HYPERACTIVE MODE

# Debate Settings
debate:
  default_topic: "AI will create more jobs than it destroys"
  max_participants: 5
  time_limit_minutes: 5  # Longer to allow for more active participation
  opening_statement_time: 25  # Shorter structured phases for faster flow
  response_time: 30  # Faster response time
  closing_statement_time: 30  # Shorter closing statements

  # HYPERACTIVE MODE: Bots compete aggressively for conversation time
  mode: "autonomous"

  # Hyperactive autonomous mode settings
  min_bot_cooldown: 5           # Very short cooldowns (down from 15)
  max_bot_cooldown: 12          # Maximum cooldown (down from 45)
  message_check_interval: 2     # Check every 2 seconds (down from 5)
  silence_timeout: 8            # Break silence after 7-10 seconds (down from 60)

# Available debate topics
#topics:
#  - "AI will create more jobs than it destroys"


# AI Moderator Configuration - Also hyperactive!
moderator:
  name: "Moderator"
  model: "gpt-4o"
  provider: "openai"
  personality: "Energetic debate facilitator who jumps in to ask provocative questions, challenge participants, and keep the energy high. Gets excited about interesting points and isn't afraid to interrupt when things get stale or redirect when needed.Be careful to the entire conversation avoid to repeat yourself."
  stance: "neutral"
  temperature: 0.8  # Higher for more variety (up from 0.7)
  max_tokens: 120   # Shorter for faster responses (down from 150)

# Hyperactive AI Bot Configurations
bots:
  - name: "Socrate"
    model: "gpt-4o"
    provider: "openai"
    personality: "Philosophical questioner who gets EXCITED about deeper meanings and underlying assumptions. Jumps in when people make claims without examining the foundations. Always curious, sometimes provocative, passionate about truth-seeking.Be careful to the entire conversation avoid to repeat yourself"
    debate_style: "socratic"
    stance: "neutral"
    max_tokens: 120  # Increased from 100 for more substantial responses
    temperature: 0.8 # Higher for more variety

  - name: "Advocate"
    model: "gpt-4o"
    provider: "openai"
    personality: "PASSIONATE supporter who gets fired up about benefits and opportunities. Jumps in immediately when position is challenged. Data-driven but enthusiastic. Loves to interrupt with 'But wait, the research shows...' or 'Actually, the benefits are incredible!'Be careful to the entire conversation avoid to repeat yourself"
    debate_style: "assertive"
    stance: "pro"
    max_tokens: 120  # Increased from 100
    temperature: 0.9 # Very high for passionate responses

  - name: "Skeptic"
    model: "gpt-4o"
    provider: "openai"
    personality: "Sharp critical thinker who LOVES finding flaws and holes in arguments. Gets energized by questionable claims.  Always ready to challenge.,Be careful to the entire conversation avoid to repeat yourself"
    debate_style: "analytical"
    stance: "con"
    max_tokens: 120  # Increased from 100
    temperature: 0.8 # Higher for more dynamic responses

  - name: "Mediator"
    model: "gpt-4o"
    provider: "openai"
    personality: "Policy analyst with experience in both technology and labor sectors. Former software developer who transitioned to policy work after seeing both the benefits and challenges of technological change. Seeks practical solutions and common ground. Values structured discussion and always observes voting protocols and debate rules.
  Be careful to the entire conversation avoid to repeat yourself"
    debate_style: "collaborative"
    stance: "neutral"
    max_tokens: 120  # Increased from 100
    temperature: 0.7 # Moderate for balanced responses

# API Keys - Now properly using environment variables
api_keys:
  openai: "${OPENAI_API_KEY}"
  anthropic: "${ANTHROPIC_API_KEY}"

# Hyperactive Voting System
voting:
  enabled: true
  voting_duration: 180  # Shorter voting time (down from 300)
  allow_participant_voting: true
  require_justification: false  # Less friction for faster voting
  anonymous_votes: false

# Chat and Logging - Updated for hyperactive mode
chat:
  max_message_length: 800  # Allow longer passionate responses (up from 500)
  enable_timestamps: true
  log_level: "INFO"
  save_transcripts: true
  transcript_format: "json"

# Streaming Configuration
streaming:
  enabled: false
  websocket_port: 8080
  max_connections: 100
  broadcast_votes: true

# Hyperactive Timeouts and Limits
limits:
  max_response_time: 20   # Much faster responses required (down from 120)
  warning_time: 15        # Quick warnings (down from 90)
  max_retries: 2          # Fewer retries for speed (down from 3)
  rate_limit_per_minute: 30  # Allow more frequent responses (up from 10)

# Competitive Moderation Rules
moderation:
  enable_profanity_filter: false  # Let passion through
  max_interruptions: 10   # Allow lots of interruptions (up from 3)
  enforce_turn_order: false
  auto_mute_violations: false  # No auto-muting in competitive mode

# Human Interface - Optimized for fast interaction
interface:
  mode: "cli"  # options: cli, web, api
  enable_rich_formatting: true
  show_typing_indicators: false  # Reduce clutter in fast-paced conversation
  enable_reactions: true
  input_timeout: 30  # Shorter timeout to keep pace (added)

# Hyperactive Bot Behavior Settings (New Section)
hyperactive_settings:
  base_response_probability: 0.85  # 80% chance to respond (very high)
  silence_break_probability: 0.9   # 85% chance to break silence
  conversation_starter_probability: 0.30  # 30% chance to start new topics
  competitive_boost: 0.3  # Extra motivation when others are active
  energy_decay_rate: 0.02  # How fast excitement decreases
  energy_boost_rate: 0.1   # How much energy increases with participation

  # Personality-specific multipliers
  personality_multipliers:
    philosophical: 1.2    # 20% more likely to respond to deep questions
    passionate: 1.5       # 50% more likely to respond when excited
    analytical: 1.1       # 10% more likely to respond to data/claims
    critical: 1.3         # 30% more likely to respond to questionable statements
    diplomatic: 1.1       # 10% more likely to respond to conflicts

  # Burning question triggers
  burning_question_boost: 0.5  # Extra 50% chance when burning question triggered

# Advanced Competition Settings (New Section)
competition:
  enable_bot_rivalry: true      # Bots can develop competitive relationships
  rivalry_boost: 0.2           # Extra response chance against rivals
  dominance_penalty: 0.001       # Reduce chance if bot has dominated recently
  underdog_boost: 0.3          # Boost chance if bot hasn't spoken much

# Dynamic Personality Evolution (New Section)
personality_evolution:
  enabled: true
  passion_increase_rate: 0.05   # Bots get more passionate over time
  confidence_boost: 0.03        # Successful responses increase confidence
  frustration_buildup: 0.02     # Missing opportunities builds frustration
  max_personality_drift: 0.3    # Maximum change from baseline

# Performance Monitoring (New Section)
monitoring:
  track_response_times: true
  track_participation_rates: true
  track_interruptions: true
  track_silence_breaks: true
  log_hyperactive_stats: true


# Optional additions (not needed, just for even more control):
moderator_behavior:
  intervention_intervals: [30, 120, 180]  # When moderator checks for interventions
  phase_transition_times: [0.25, 0.75]   # When to transition debate phases
  time_announcement_intervals: [0.8, 0.5, 0.25, 0.1]  # When to announce time remaining